[package]
name = "personal-organizer-server"
version = "0.1.0"
authors = ["Tiffany Bennett <tiffnixen@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.7"
actix-web = "0.7"
serde_derive = "1.0"
serde = "1.0"
futures = "0.1"

[dependencies.rusqlite]
version = "0.17"
features = [ "bundled" ]
